### ISSUE TITLE
Problème d'image sur edge

### ISSUE THREAD

**Issue by Avaritiainme** [REUZIA/OpenBar#3]
![msedge_sWkEMxoOlO](https://github.com/REUZIA/OpenBar/assets/102719175/c2fb7700-d308-4a41-a62a-5c3713996f19)

L'image n'apparait pas et le nom semble mauvais

**Comment by Pierre-Melo** [comment]
C'est une entrée test, c'est normal que le nom n'apparait pas sur celle-ci, obtient tu la même chose sur les autre entrée ?
